development:
  secret_key_base: 2a8f5512db14a6a2ca89bddfcbf4078bc7688b70d1b9754188ffe9998ac89f9a5d83121866309c8e53ff02a61c48fbdf7a79096a75f0d2473c76213127807192

test:
  secret_key_base: 24402e3e03edb2e75385b370f6c51b7c8a7f18291ecff33cb1f650801ac4c4dccdf723b534e210caa442ded96390cb8c4778220cedb132cc114a92595d5c5c2f

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
